/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRoomsRouteImport } from './routes/_app.rooms'
import { Route as AppPortalRouteImport } from './routes/_app.portal'
import { Route as AppGuestsRouteImport } from './routes/_app.guests'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppBookingsRouteImport } from './routes/_app.bookings'
import { Route as AppBillingRouteImport } from './routes/_app.billing'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoomsRoute = AppRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AppRoute,
} as any)
const AppPortalRoute = AppPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AppRoute,
} as any)
const AppGuestsRoute = AppGuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBookingsRoute = AppBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/billing': typeof AppBillingRoute
  '/bookings': typeof AppBookingsRoute
  '/dashboard': typeof AppDashboardRoute
  '/guests': typeof AppGuestsRoute
  '/portal': typeof AppPortalRoute
  '/rooms': typeof AppRoomsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/billing': typeof AppBillingRoute
  '/bookings': typeof AppBookingsRoute
  '/dashboard': typeof AppDashboardRoute
  '/guests': typeof AppGuestsRoute
  '/portal': typeof AppPortalRoute
  '/rooms': typeof AppRoomsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/bookings': typeof AppBookingsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/guests': typeof AppGuestsRoute
  '/_app/portal': typeof AppPortalRoute
  '/_app/rooms': typeof AppRoomsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/billing'
    | '/bookings'
    | '/dashboard'
    | '/guests'
    | '/portal'
    | '/rooms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/billing'
    | '/bookings'
    | '/dashboard'
    | '/guests'
    | '/portal'
    | '/rooms'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/billing'
    | '/_app/bookings'
    | '/_app/dashboard'
    | '/_app/guests'
    | '/_app/portal'
    | '/_app/rooms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/rooms': {
      id: '/_app/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AppRoomsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portal': {
      id: '/_app/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AppPortalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guests': {
      id: '/_app/guests'
      path: '/guests'
      fullPath: '/guests'
      preLoaderRoute: typeof AppGuestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bookings': {
      id: '/_app/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AppBookingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBillingRoute: typeof AppBillingRoute
  AppBookingsRoute: typeof AppBookingsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppGuestsRoute: typeof AppGuestsRoute
  AppPortalRoute: typeof AppPortalRoute
  AppRoomsRoute: typeof AppRoomsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBillingRoute: AppBillingRoute,
  AppBookingsRoute: AppBookingsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppGuestsRoute: AppGuestsRoute,
  AppPortalRoute: AppPortalRoute,
  AppRoomsRoute: AppRoomsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
